import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";
import SideBar from "@/components/Sidebar";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <div className="flex flex-row">
            <SideBar />
            <div className="flex flex-col flex-auto">
              <Navbar/>
              <div className="">
              {children}
              </div>
             
             
            </div>
          </div>
        </body>
      </Providers>
    </html>
  );
}
