import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";
import SideBar from "@/components/Sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import { ToastContainer } from "react-toastify";
import ContextWrapper from "./ContextWrapper";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { getUser } = getKindeServerSession();  
  const user: any = await getUser();

  return (
    <html lang="en">
      <Providers>
        {/* <OnlineUsers> */}
        <body className={inter.className}>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
          <div className="flex flex-row">
            <SideBar />
            <div className="flex flex-col flex-auto">
              {/* @ts-expect-error Server Component */}
              <Navbar />
              <ContextWrapper userId={user?.id}>{children}</ContextWrapper>
            </div>
          </div>
        </body>
        {/* </OnlineUsers> */}
      </Providers>
    </html>
  );
}
